version: '3.5'

services:
  mysql:
    container_name: mysql_container
    restart: always
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeit}
      MYSQL_USER: ${MYSQL_USER:-fastcoretux}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-changeit}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME:-fastcoretux}
    volumes:
      - ~/Development/docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3308:3306"
  
  adminer:
    container_name: adminer_container
    image: adminer    
    ports:      
      - "${ADMINER_PORT:-8080}:8080"
